### ISSUE TITLE
Confusion about setOnHost

### ISSUE THREAD

**Issue by DanielSokil** [fovea-org/fovea#18]
Could you please explain what `@setOnHost` does when setting properties? I'm a bit confused about that.
Thanks.

**Comment by wessberg** [comment]
Hi there!
Thanks for trying out Fovea! 👍 

Documentation is still being written (Fovea hasn't even been formally announced yet), but until it is out, I can give you some guidance here.

If a `@prop` has the `@setOnHost` decorator, its value will be set on the host element as an attribute.

For example, consider this:

```typescript
import {prop, setOnHost} from "@fovea/core";

class MyElement extends HTMLElement {
    @prop @setOnHost name = "Daniel";
}
```

In the DOM, `MyElement` will render as:

```html
<my-element name="Daniel"></my-element>
```

There can be many reasons why you want this. Some may be for styling purposes, for example:

```css
:host([name="Daniel"]) {
    background: green;
}
```

...And some may be for other reasons such as accessibility.

**Comment by DanielSokil** [comment]
Wow, This is nice. Thanks so much!
