### ISSUE TITLE
npx: command not found: cli

### ISSUE THREAD

**Issue by DanielSokil** [fovea-org/fovea#28]
I tried running `@fovea/cli` as mentioned in:
https://github.com/fovea-org/fovea/blob/master/packages/cli/README.md

```bash
$ npm install @fovea/cli
....
Binary found at /home/danielsokil/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
npm WARN danielsokil No description
npm WARN danielsokil No repository field.
npm WARN danielsokil No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @fovea/cli@1.0.132
added 1024 packages from 778 contributors, removed 93 packages, moved 2 packages and audited 11266 packages in 16.868s
found 0 vulnerabilities


$ npx @fovea/cli
info looking for cached prebuild @ /home/danielsokil/.npm/_prebuilds/9a175d-iltorb-v2.4.0-node-v64-linux-x64.tar.gz
info found cached prebuild 
info unpacking @ /home/danielsokil/.npm/_prebuilds/9a175d-iltorb-v2.4.0-node-v64-linux-x64.tar.gz
info unpack resolved to /home/danielsokil/.npm/_npx/16889/lib/node_modules/@fovea/cli/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /home/danielsokil/.npm/_npx/16889/lib/node_modules/@fovea/cli/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!
info sharp Using cached /home/danielsokil/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
npx: command not found: cli
```

What am I doing wrong?

**Comment by wessberg** [comment]
Hmm, strange. I'll look into it. Thanks for reporting it. In the meantime, you can get around this by adding a script to your `package.json` that uses the CLI:

```json
{
   "scripts": {
        "cli": "fovea"
    }
}
```

Then you can run it from the command line. For example, to create a new Fovea app with the CLI:

```
npm run cli -- create my-app
```

**Comment by DanielSokil** [comment]
@wessberg 
It still results in an error:
```bash
$ npm run cli -- create my-app

> fovea-app@1.0.0 cli /home/danielsokil/Desktop/Lab/JavaScript/fovea-app
> fovea "create" "my-app"

/usr/bin/env: ‘node --no-warnings’: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fovea-app@1.0.0 cli: `fovea "create" "my-app"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fovea-app@1.0.0 cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danielsokil/.npm/_logs/2018-09-22T09_29_26_722Z-debug.log
```

**Comment by wessberg** [comment]
It sounds like you're running Ubuntu Linux and is running into issues with nodejs vs node in your path. I've run into issues with this quite sometimes when using nvm.

It's

Try this:

`ln -s /usr/bin/nodejs /usr/bin/node`

You may need to place sudo in front of it.

**Comment by DanielSokil** [comment]
@wessberg
Yeah, I'm running a distribution based on Ubuntu.
```bash
$ sudo ln -s /usr/bin/nodejs /usr/bin/node
ln: failed to create symbolic link '/usr/bin/node': File exists

$ sudo ln -sf /usr/bin/nodejs /usr/bin/node
ln: '/usr/bin/nodejs' and '/usr/bin/node' are the same file
```

**Comment by wessberg** [comment]
Yes, there are some issues on Ubuntu with node and nvm due to these things. It causes some issues such as with NPM packages that ship binaries such as is the case with @fovea/cli (and frankly most (...all?) other packages that ships binaries that execute a binary with node). There's nothing I can do about this here as the de-facto standard with NPM packages is to execute from `#!/usr/bin/env node`.

I would suggest you look into how to get around these issues on Ubuntu with nodejs vs node and symlinking.

Feel free to get back to me if there's anything else I can do here.

**Comment by wessberg** [comment]
The `create` command already creates a tiny boilerplate app (with async routing, etc), but I'm looking into making it possible to select between multiple templates for starter apps!
